//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/World/map.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// LDtk Enum for MapEnums
/// </summary>
public enum RoleSwap
{
    Unset,
    Baloon1,
    Baloon2,
    Block1,
    Player,
    Spike,
    Ice
}